### ISSUE TITLE
Hi, any update for Dpt Air

### ISSUE THREAD

**Issue by JiangXL** [YLiLarry/dpt-rp1-cpp#1]
Any update for Dpt Air? Dpt Air is a great software!

**Comment by yuliswe** [comment]
Hello, thank you for liking my app. :p what can I do for you?

**Comment by JiangXL** [comment]
Thank your reply. Where can I find the GUI program which demonstrate in your github page? I almost work under a Fedora machine, your project is tantalizing and elegant for linux environment.

**Comment by yuliswe** [comment]
Hi, the source code is here:
https://github.com/ylilarry/dpt-air-mac

There hasn't been enough interest in this project, so I haven't looked at it for 2 years.
Apple does not allow me to release the app via the App Store because it uses a helper app.
You can try building in on your own. Contribution is welcomed.
